wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.19
    framework: huggingface
    huggingface_version: 3.2.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      2:
      - 1
      - 3
      - 5
      - 11
      4: 3.7.5
      5: 0.10.19
      6: 3.2.0
